/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppInvoicesRouteImport } from './routes/_authenticated/app.invoices'
import { Route as AuthenticatedAppDriversRouteImport } from './routes/_authenticated/app.drivers'
import { Route as AuthenticatedAppDriverProfileRouteImport } from './routes/_authenticated/app.driver-profile'
import { Route as AuthenticatedAppAvailableLoadsRouteImport } from './routes/_authenticated/app.available-loads'
import { Route as AuthenticatedAppShipmentsIndexRouteImport } from './routes/_authenticated/app.shipments.index'
import { Route as AuthenticatedAppMyLoadsIndexRouteImport } from './routes/_authenticated/app.my-loads.index'
import { Route as AuthenticatedAppShipmentsNewRouteImport } from './routes/_authenticated/app.shipments.new'
import { Route as AuthenticatedAppShipmentsIdRouteImport } from './routes/_authenticated/app.shipments.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInvoicesRoute =
  AuthenticatedAppInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDriversRoute = AuthenticatedAppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDriverProfileRoute =
  AuthenticatedAppDriverProfileRouteImport.update({
    id: '/driver-profile',
    path: '/driver-profile',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAvailableLoadsRoute =
  AuthenticatedAppAvailableLoadsRouteImport.update({
    id: '/available-loads',
    path: '/available-loads',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppShipmentsIndexRoute =
  AuthenticatedAppShipmentsIndexRouteImport.update({
    id: '/shipments/',
    path: '/shipments/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMyLoadsIndexRoute =
  AuthenticatedAppMyLoadsIndexRouteImport.update({
    id: '/my-loads/',
    path: '/my-loads/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppShipmentsNewRoute =
  AuthenticatedAppShipmentsNewRouteImport.update({
    id: '/shipments/new',
    path: '/shipments/new',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppShipmentsIdRoute =
  AuthenticatedAppShipmentsIdRouteImport.update({
    id: '/shipments/$id',
    path: '/shipments/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/available-loads': typeof AuthenticatedAppAvailableLoadsRoute
  '/app/driver-profile': typeof AuthenticatedAppDriverProfileRoute
  '/app/drivers': typeof AuthenticatedAppDriversRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/shipments/$id': typeof AuthenticatedAppShipmentsIdRoute
  '/app/shipments/new': typeof AuthenticatedAppShipmentsNewRoute
  '/app/my-loads/': typeof AuthenticatedAppMyLoadsIndexRoute
  '/app/shipments/': typeof AuthenticatedAppShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/available-loads': typeof AuthenticatedAppAvailableLoadsRoute
  '/app/driver-profile': typeof AuthenticatedAppDriverProfileRoute
  '/app/drivers': typeof AuthenticatedAppDriversRoute
  '/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/shipments/$id': typeof AuthenticatedAppShipmentsIdRoute
  '/app/shipments/new': typeof AuthenticatedAppShipmentsNewRoute
  '/app/my-loads': typeof AuthenticatedAppMyLoadsIndexRoute
  '/app/shipments': typeof AuthenticatedAppShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/available-loads': typeof AuthenticatedAppAvailableLoadsRoute
  '/_authenticated/app/driver-profile': typeof AuthenticatedAppDriverProfileRoute
  '/_authenticated/app/drivers': typeof AuthenticatedAppDriversRoute
  '/_authenticated/app/invoices': typeof AuthenticatedAppInvoicesRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/shipments/$id': typeof AuthenticatedAppShipmentsIdRoute
  '/_authenticated/app/shipments/new': typeof AuthenticatedAppShipmentsNewRoute
  '/_authenticated/app/my-loads/': typeof AuthenticatedAppMyLoadsIndexRoute
  '/_authenticated/app/shipments/': typeof AuthenticatedAppShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/available-loads'
    | '/app/driver-profile'
    | '/app/drivers'
    | '/app/invoices'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/reports'
    | '/app/'
    | '/app/shipments/$id'
    | '/app/shipments/new'
    | '/app/my-loads/'
    | '/app/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/available-loads'
    | '/app/driver-profile'
    | '/app/drivers'
    | '/app/invoices'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/reports'
    | '/app'
    | '/app/shipments/$id'
    | '/app/shipments/new'
    | '/app/my-loads'
    | '/app/shipments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/available-loads'
    | '/_authenticated/app/driver-profile'
    | '/_authenticated/app/drivers'
    | '/_authenticated/app/invoices'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/'
    | '/_authenticated/app/shipments/$id'
    | '/_authenticated/app/shipments/new'
    | '/_authenticated/app/my-loads/'
    | '/_authenticated/app/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invoices': {
      id: '/_authenticated/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AuthenticatedAppInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/drivers': {
      id: '/_authenticated/app/drivers'
      path: '/drivers'
      fullPath: '/app/drivers'
      preLoaderRoute: typeof AuthenticatedAppDriversRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/driver-profile': {
      id: '/_authenticated/app/driver-profile'
      path: '/driver-profile'
      fullPath: '/app/driver-profile'
      preLoaderRoute: typeof AuthenticatedAppDriverProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/available-loads': {
      id: '/_authenticated/app/available-loads'
      path: '/available-loads'
      fullPath: '/app/available-loads'
      preLoaderRoute: typeof AuthenticatedAppAvailableLoadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/shipments/': {
      id: '/_authenticated/app/shipments/'
      path: '/shipments'
      fullPath: '/app/shipments/'
      preLoaderRoute: typeof AuthenticatedAppShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/my-loads/': {
      id: '/_authenticated/app/my-loads/'
      path: '/my-loads'
      fullPath: '/app/my-loads/'
      preLoaderRoute: typeof AuthenticatedAppMyLoadsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/shipments/new': {
      id: '/_authenticated/app/shipments/new'
      path: '/shipments/new'
      fullPath: '/app/shipments/new'
      preLoaderRoute: typeof AuthenticatedAppShipmentsNewRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/shipments/$id': {
      id: '/_authenticated/app/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/app/shipments/$id'
      preLoaderRoute: typeof AuthenticatedAppShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAvailableLoadsRoute: typeof AuthenticatedAppAvailableLoadsRoute
  AuthenticatedAppDriverProfileRoute: typeof AuthenticatedAppDriverProfileRoute
  AuthenticatedAppDriversRoute: typeof AuthenticatedAppDriversRoute
  AuthenticatedAppInvoicesRoute: typeof AuthenticatedAppInvoicesRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppShipmentsIdRoute: typeof AuthenticatedAppShipmentsIdRoute
  AuthenticatedAppShipmentsNewRoute: typeof AuthenticatedAppShipmentsNewRoute
  AuthenticatedAppMyLoadsIndexRoute: typeof AuthenticatedAppMyLoadsIndexRoute
  AuthenticatedAppShipmentsIndexRoute: typeof AuthenticatedAppShipmentsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAvailableLoadsRoute: AuthenticatedAppAvailableLoadsRoute,
  AuthenticatedAppDriverProfileRoute: AuthenticatedAppDriverProfileRoute,
  AuthenticatedAppDriversRoute: AuthenticatedAppDriversRoute,
  AuthenticatedAppInvoicesRoute: AuthenticatedAppInvoicesRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppShipmentsIdRoute: AuthenticatedAppShipmentsIdRoute,
  AuthenticatedAppShipmentsNewRoute: AuthenticatedAppShipmentsNewRoute,
  AuthenticatedAppMyLoadsIndexRoute: AuthenticatedAppMyLoadsIndexRoute,
  AuthenticatedAppShipmentsIndexRoute: AuthenticatedAppShipmentsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
